In [2]:
def chat(name, address, track, amount = 3454):
    print("Welcome Mr " + name +" do you still live at " + address + " ,your track is still " + track)

chat("Mike", "Estate 6", "Web Dev")

Welcome Mr Mike do you still live at Estate 6 ,your track is still Web Dev


In [3]:
for man in (1,2,3,4,5,6,7,8,9,0):
    print(man)

1
2
3
4
5
6
7
8
9
0


In [4]:
x = 1
while x <= 5:
    print(x)
    x += 1

1
2
3
4
5


In [5]:
for car in range(2, 15, 4):
    print(car)

2
6
10
14


In [6]:
address = "grace bill road eket"
address.lower()
address.title()
address.upper()
address.split()

['grace', 'bill', 'road', 'eket']

In [7]:
fruit = "watermelon"
fruit.startswith("w")

True

In [8]:
name = "Jacob Paul"
age = 55
jkl = name.replace("Jacob", "Abas")
print(jkl)

Abas Paul


In [9]:
print("My name is {} and I am {} years old ").__format__

My name is {} and I am {} years old 


<function NoneType.__format__(self, format_spec, /)>

These are methods:
.len()
.sum()
.type()
.min()
.max()

In [10]:
marks_1 = (23, 23, "absent", 35, "missing", 89)
items = ("mat", "cup",)

In [11]:
A = {4,2,3,9}
B = {4,5,2,1}
C = B - A
C

{1, 5}

In [12]:
top_sports = {
    "Alex": "Football",
    "Joyy": "Basketball",
    "Dan": "Tennis"
}

### Numpy

* It is a libary (collection of already written codes)
* It helps us to work with numbers
* It allows fast mathematical operations in big amounts of data

In [13]:
import numpy as np

In [14]:
arr1 = np.array([1,2,3,4,5,6])

arr1

array([1, 2, 3, 4, 5, 6])

In [15]:
c = np.array([2,4,6,8])
d = np.array([3,6,9,9])

print( c + d)

[ 5 10 15 17]


In [16]:
c.size

4

In [17]:
c.dtype

dtype('int64')

In [18]:
big_num = c[c > 2]
big_num

array([4, 6, 8])

In [19]:
#Matrix is a 2D table of numbers
A = np.array([[9,7,6,5],
              [4,6,5,1]])

B = np.array([[5,6],         
              [7,8]])

print(A.shape)
print(A.size)

(2, 4)
8


In [20]:
print(np.sum(A))
print(np.mean(A))
print(np.transpose(A))

43
5.375
[[9 4]
 [7 6]
 [6 5]
 [5 1]]


In [21]:
np.where(A > 5, "So High","Low")

array([['So High', 'So High', 'So High', 'Low'],
       ['Low', 'So High', 'Low', 'Low']], dtype='<U7')

In [22]:
print(np.random.rand(2,3))
print(np.random.randint(15,89,12))

[[0.30162582 0.56064051 0.90666182]
 [0.55341444 0.12473305 0.01242958]]
[71 84 32 55 63 54 38 16 66 67 78 27]


In [26]:
scores = np.array([[85,55,66],
                   [66,45,90],
                   [72,92,80]])

print("  M","  E","  S")

print(scores)

  M   E   S
[[85 55 66]
 [66 45 90]
 [72 92 80]]


In [32]:
print(scores[:,2])
print(scores[1,1])

[66 90 80]
45


In [ ]:
np.sum(scores[1,:])

np.int64(201)